name: Deploy to InfinityFree

on:
  push:
    branches:
      # Solo se desplegara desde la rama production ojo
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: üì• Checkout repository
        uses: actions/checkout@v3

      - name: üì¶ Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: üõ†Ô∏è Publicar vistas de errores
        run: php artisan vendor:publish --tag=laravel-errors --force
        
      - name: üîß Optimize Laravel
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FPT_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./" 
          server-dir: "/gestionriesgossig.infinityfreeapp.com/htdocs/" # Ojo se cambia de ruta por problemas con el domino rf.gd.... (incompatibilidad)
          exclude: |
            **/vendor/**
            **/.git*
            **/node_modules/**
            **/tests/**
            **/.github/**
            README.md